
let cityList = document.getElementById("city-list");
console.log(cityList);

cityList.addEventListener("change", changeCity);

function changeCity(event){

  let city = event.target.value;

  //ensures every first letter is capitalised
  //splits into separate words
  //' ' ensures there is space between
  //https://www.w3schools.com/js/js_maps.asp
  let formattedCity = city 
  .split(' ')
  .map(word => word[0]
  .toUpperCase() + word.slice(1))
  .join(' ');

  let timezones = {
Dubai: "Asia/Dubai",
Kabul: "Asia/Kabul",
Yerevan: "Asia/Yerevan",
Baku: "Asia/Baku",
Dhaka: "Asia/Dhaka",
Brunei: "Asia/Brunei",
Thimphu: "Asia/Thimphu",
Shanghai: "Asia/Shanghai",
Urumqi: "Asia/Urumqi",
Nicosia: "Asia/Nicosia",
Famagusta: "Asia/Famagusta",
Tbilisi: "Asia/Tbilisi",
Hong_Kong: "Asia/Hong_Kong",
Jakarta: "Asia/Jakarta",
Pontianak: "Asia/Pontianak",
Makassar: "Asia/Makassar",
Jayapura: "Asia/Jayapura",
Jerusalem: "Asia/Jerusalem",
Kolkata: "Asia/Kolkata",
Baghdad: "Asia/Baghdad",
Tehran: "Asia/Tehran",
Amman: "Asia/Amman",
Tokyo: "Asia/Tokyo",
Bishkek: "Asia/Bishkek",
Pyongyang: "Asia/Pyongyang",
Seoul: "Asia/Seoul",
Almaty: "Asia/Almaty",
Qyzylorda: "Asia/Qyzylorda",
Qostanay: "Asia/Qostanay",
Aqtobe: "Asia/Aqtobe",
Aqtau: "Asia/Aqtau",
Atyrau: "Asia/Atyrau",
Oral: "Asia/Oral",
Beirut: "Asia/Beirut",
Colombo: "Asia/Colombo",
Yangon: "Asia/Yangon",
Ulaanbaatar: "Asia/Ulaanbaatar",
Hovd: "Asia/Hovd",
Choibalsan: "Asia/Choibalsan",
Macau: "Asia/Macau",
Kuala_Lumpur: "Asia/Kuala_Lumpur",
Kuching: "Asia/Kuching",
Karachi: "Asia/Karachi",
Gaza: "Asia/Gaza",
Hebron: "Asia/Hebron",
Kathmandu: "Asia/Kathmandu",
Yekaterinburg: "Asia/Yekaterinburg",
Qatar: "Asia/Qatar",
Omsk: "Asia/Omsk",
Novosibirsk: "Asia/Novosibirsk",
Barnaul: "Asia/Barnaul",
Tomsk: "Asia/Tomsk",
Novokuznetsk: "Asia/Novokuznetsk",
Krasnoyarsk: "Asia/Krasnoyarsk",
Irkutsk: "Asia/Irkutsk",
Chita: "Asia/Chita",
Yakutsk: "Asia/Yakutsk",
Khandyga: "Asia/Khandyga",
Vladivostok: "Asia/Vladivostok",
Ust_Nera: "Asia/Ust-Nera",
Singapore: "Asia/Singapore",
Magadan: "Asia/Magadan",
Sakhalin: "Asia/Sakhalin",
Srednekolymsk: "Asia/Srednekolymsk",
Kamchatka: "Asia/Kamchatka",
Anadyr: "Asia/Anadyr",
Bangkok: "Asia/Bangkok",
Dushanbe: "Asia/Dushanbe",
Taipei: "Asia/Taipei",
Dili: "Asia/Dili",
Ashgabat: "Asia/Ashgabat",
Damascus: "Asia/Damascus",
Riyadh: "Asia/Riyadh",
Samarkand: "Asia/Samarkand",
Tashkent: "Asia/Tashkent",
Ho_Chi_Minh: "Asia/Ho_Chi_Minh",
Andorra: "Europe/Andorra",
Tirane: "Europe/Tirane",
Vienna: "Europe/Vienna",
Brussels: "Europe/Brussels",
Sofia: "Europe/Sofia",
Minsk: "Europe/Minsk",
Zurich: "Europe/Zurich",
Prague: "Europe/Prague",
Berlin: "Europe/Berlin",
Copenhagen: "Europe/Copenhagen",
Tallinn: "Europe/Tallinn",
Madrid: "Europe/Madrid",
Helsinki: "Europe/Helsinki",
Paris: "Europe/Paris",
London: "Europe/London",
Gibraltar: "Europe/Gibraltar",
Athens: "Europe/Athens",
Budapest: "Europe/Budapest",
Dublin: "Europe/Dublin",
Rome: "Europe/Rome",
Vilnius: "Europe/Vilnius",
Luxembourg: "Europe/Luxembourg",
Riga: "Europe/Riga",
Monaco: "Europe/Monaco",
Chisinau: "Europe/Chisinau",
Malta: "Europe/Malta",
Amsterdam: "Europe/Amsterdam",
Oslo: "Europe/Oslo",
Warsaw: "Europe/Warsaw",
Lisbon: "Europe/Lisbon",
Bucharest: "Europe/Bucharest",
Belgrade: "Europe/Belgrade",
Kaliningrad: "Europe/Kaliningrad",
Moscow: "Europe/Moscow",
Simferopol: "Europe/Simferopol",
Kirov: "Europe/Kirov",
Astrakhan: "Europe/Astrakhan",
Volgograd: "Europe/Volgograd",
Saratov: "Europe/Saratov",
Ulyanovsk: "Europe/Ulyanovsk",
Samara: "Europe/Samara",
Stockholm: "Europe/Stockholm",
Istanbul: "Europe/Istanbul",
Kiev: "Europe/Kiev",
Uzhgorod: "Europe/Uzhgorod",
Zaporozhye: "Europe/Zaporozhye",
Casey: "Antarctica/Casey",
Davis: "Antarctica/Davis",
DumontDUrville: "Antarctica/DumontDUrville",
Mawson: "Antarctica/Mawson",
Palmer: "Antarctica/Palmer",
Rothera: "Antarctica/Rothera",
Syowa: "Antarctica/Syowa",
Troll: "Antarctica/Troll",
Vostok: "Antarctica/Vostok",
Macquarie: "Antarctica/Macquarie",
Buenos_Aires: "America/Argentina/Buenos_Aires",
Cordoba: "America/Argentina/Cordoba",
Salta: "America/Argentina/Salta",
Jujuy: "America/Argentina/Jujuy",
Tucuman: "America/Argentina/Tucuman",
Catamarca: "America/Argentina/Catamarca",
La_Rioja: "America/Argentina/La_Rioja",
San_Juan: "America/Argentina/San_Juan",
Mendoza: "America/Argentina/Mendoza",
San_Luis: "America/Argentina/San_Luis",
Rio_Gallegos: "America/Argentina/Rio_Gallegos",
Ushuaia: "America/Argentina/Ushuaia",
Barbados: "America/Barbados",
La_Paz: "America/La_Paz",
Belem: "America/Belem",
Fortaleza: "America/Fortaleza",
Recife: "America/Recife",
Araguaina: "America/Araguaina",
Maceio: "America/Maceio",
Bahia: "America/Bahia",
Sao_Paulo: "America/Sao_Paulo",
Campo_Grande: "America/Campo_Grande",
Cuiaba: "America/Cuiaba",
Porto_Velho: "America/Porto_Velho",
Boa_Vista: "America/Boa_Vista",
Manaus: "America/Manaus",
Eirunepe: "America/Eirunepe",
Rio_Branco: "America/Rio_Branco",
Nassau: "America/Nassau",
Belize: "America/Belize",
St_Johns: "America/St_Johns",
Halifax: "America/Halifax",
Glace_Bay: "America/Glace_Bay",
Moncton: "America/Moncton",
Goose_Bay: "America/Goose_Bay",
Blanc_Sablon: "America/Blanc-Sablon",
Toronto: "America/Toronto",
Nipigon: "America/Nipigon",
Thunder_Bay: "America/Thunder_Bay",
Iqaluit: "America/Iqaluit",
Pangnirtung: "America/Pangnirtung",
Atikokan: "America/Atikokan",
Winnipeg: "America/Winnipeg",
Rainy_River: "America/Rainy_River",
Resolute: "America/Resolute",
Rankin_Inlet: "America/Rankin_Inlet",
Regina: "America/Regina",
Swift_Current: "America/Swift_Current",
Edmonton: "America/Edmonton",
Cambridge_Bay: "America/Cambridge_Bay",
Yellowknife: "America/Yellowknife",
Inuvik: "America/Inuvik",
Creston: "America/Creston",
Dawson_Creek: "America/Dawson_Creek",
Fort_Nelson: "America/Fort_Nelson",
Vancouver: "America/Vancouver",
Whitehorse: "America/Whitehorse",
Dawson: "America/Dawson",
Santiago: "America/Santiago",
Punta_Arenas: "America/Punta_Arenas",
Bogota: "America/Bogota",
Costa_Rica: "America/Costa_Rica",
Havana: "America/Havana",
Curacao: "America/Curacao",
Santo_Domingo: "America/Santo_Domingo",
Guayaquil: "America/Guayaquil",
Cayenne: "America/Cayenne",
Godthab: "America/Godthab",
Danmarkshavn: "America/Danmarkshavn",
Scoresbysund: "America/Scoresbysund",
Thule: "America/Thule",
Guatemala: "America/Guatemala",
Guyana: "America/Guyana",
Tegucigalpa: "America/Tegucigalpa",
Port_au_Prince: "America/Port-au-Prince",
Jamaica: "America/Jamaica",
Martinique: "America/Martinique",
Mexico_City: "America/Mexico_City",
Cancun: "America/Cancun",
Merida: "America/Merida",
Monterrey: "America/Monterrey",
Matamoros: "America/Matamoros",
Caracas: "America/Caracas",
Mazatlan: "America/Mazatlan",
Chihuahua: "America/Chihuahua",
Ojinaga: "America/Ojinaga",
Hermosillo: "America/Hermosillo",
Tijuana: "America/Tijuana",
Bahia_Banderas: "America/Bahia_Banderas",
Managua: "America/Managua",
Panama: "America/Panama",
Lima: "America/Lima",
Miquelon: "America/Miquelon",
Puerto_Rico: "America/Puerto_Rico",
El_Salvador: "America/El_Salvador",
Grand_Turk: "America/Grand_Turk",
Paramaribo: "America/Paramaribo",
Asuncion: "America/Asuncion",
Port_of_Spain: "America/Port_of_Spain",
New_York: "America/New_York",
Detroit: "America/Detroit",
Louisville: "America/Kentucky/Louisville",
Monticello: "America/Kentucky/Monticello",
Indianapolis: "America/Indiana/Indianapolis",
Vincennes: "America/Indiana/Vincennes",
Winamac: "America/Indiana/Winamac",
Marengo: "America/Indiana/Marengo",
Petersburg: "America/Indiana/Petersburg",
Vevay: "America/Indiana/Vevay",
Tell_City: "America/Indiana/Tell_City",
Knox: "America/Indiana/Knox",
Chicago: "America/Chicago",
Menominee: "America/Menominee",
Denver: "America/Denver",
Boise: "America/Boise",
Phoenix: "America/Phoenix",
Center: "America/North_Dakota/Center",
New_Salem: "America/North_Dakota/New_Salem",
Beulah: "America/North_Dakota/Beulah",
Los_Angeles: "America/Los_Angeles",
Anchorage: "America/Anchorage",
Juneau: "America/Juneau",
Sitka: "America/Sitka",
Metlakatla: "America/Metlakatla",
Yakutat: "America/Yakutat",
Nome: "America/Nome",
Adak: "America/Adak",
Montevideo: "America/Montevideo",
Pago_Pago: "Pacific/Pago_Pago",
Rarotonga: "Pacific/Rarotonga",
Easter: "Pacific/Easter",
Galapagos: "Pacific/Galapagos",
Fiji: "Pacific/Fiji",
Chuuk: "Pacific/Chuuk",
Pohnpei: "Pacific/Pohnpei",
Kosrae: "Pacific/Kosrae",
Guam: "Pacific/Guam",
Majuro: "Pacific/Majuro",
Kwajalein: "Pacific/Kwajalein",
Tarawa: "Pacific/Tarawa",
Enderbury: "Pacific/Enderbury",
Kiritimati: "Pacific/Kiritimati",
Noumea: "Pacific/Noumea",
Norfolk: "Pacific/Norfolk",
Nauru: "Pacific/Nauru",
Niue: "Pacific/Niue",
Auckland: "Pacific/Auckland",
Chatham: "Pacific/Chatham",
Tahiti: "Pacific/Tahiti",
Marquesas: "Pacific/Marquesas",
Gambier: "Pacific/Gambier",
Port_Moresby: "Pacific/Port_Moresby",
Bougainville: "Pacific/Bougainville",
Pitcairn: "Pacific/Pitcairn",
Palau: "Pacific/Palau",
Guadalcanal: "Pacific/Guadalcanal",
Fakaofo: "Pacific/Fakaofo",
Tongatapu: "Pacific/Tongatapu",
Funafuti: "Pacific/Funafuti",
Wake: "Pacific/Wake",
Honolulu: "Pacific/Honolulu",
Efate: "Pacific/Efate",
Wallis: "Pacific/Wallis",
Apia: "Pacific/Apia",
Lord_Howe: "Australia/Lord_Howe",
Hobart: "Australia/Hobart",
Currie: "Australia/Currie",
Melbourne: "Australia/Melbourne",
Sydney: "Australia/Sydney",
Broken_Hill: "Australia/Broken_Hill",
Brisbane: "Australia/Brisbane",
Lindeman: "Australia/Lindeman",
Adelaide: "Australia/Adelaide",
Darwin: "Australia/Darwin",
Perth: "Australia/Perth",
Eucla: "Australia/Eucla",
Abidjan: "Africa/Abidjan",
Algiers: "Africa/Algiers",
Cairo: "Africa/Cairo",
El_Aaiun: "Africa/El_Aaiun",
Ceuta: "Africa/Ceuta",
Accra: "Africa/Accra",
Bissau: "Africa/Bissau",
Nairobi: "Africa/Nairobi",
Monrovia: "Africa/Monrovia",
Tripoli: "Africa/Tripoli",
Casablanca: "Africa/Casablanca",
Maputo: "Africa/Maputo",
Windhoek: "Africa/Windhoek",
Lagos: "Africa/Lagos",
Khartoum: "Africa/Khartoum",
Juba: "Africa/Juba",
Sao_Tome: "Africa/Sao_Tome",
Ndjamena: "Africa/Ndjamena",
Tunis: "Africa/Tunis",
Johannesburg: "Africa/Johannesburg",
Azores: "Atlantic/Azores",
Bermuda: "Atlantic/Bermuda",
Madeira: "Atlantic/Madeira",
Cape_Verde: "Atlantic/Cape_Verde",
Canary: "Atlantic/Canary",
Stanley: "Atlantic/Stanley",
Faroe: "Atlantic/Faroe",
South_Georgia: "Atlantic/South_Georgia",
Reykjavik: "Atlantic/Reykjavik",
Cocos: "Indian/Cocos",
Christmas: "Indian/Christmas",
Chagos: "Indian/Chagos",
Mauritius: "Indian/Mauritius",
Maldives: "Indian/Maldives",
Mahe: "Indian/Mahe",
Reunion: "Indian/Reunion",
Kerguelen: "Indian/Kerguelen",
};

let timezone = timezones[formattedCity];
let cityTime = moment.tz(timezone).format("dddd, Do MMMM, hh:mm A");
let displayCity = document.getElementById("display-city");
displayCity.innerHTML = `The date and time in ${formattedCity} is <span class="time-element">${cityTime}</span>`;
callWeatherApi(formattedCity);
callFactApi(formattedCity);
}

const apiKey = "ff3f6c762d03ea64t3ab6978450d240o";

//function callApi(endpoint, callback) { // more efficient method
//  axios.get(endpoint).then(callback); // as it condenses api calls. DRY.
//}
//function callWeatherApi(city) {
 // let api = https://api.shecodes.io/weather/v1/current?query=${city}&key=${apiKey};
  //callApi(api, showWeather);
//}
//function callFactApi(query) {
  ///let api = https://api.shecodes.io/ai/v1/generate?prompt=give_me_an_obscure_fact_about_${encodeURIComponent(query)}&context=output in basic HTML only use br tag&key=${apiKey};
  //callApi(api, showFact);
//}

function callWeatherApi(city) {
let api = `https://api.shecodes.io/weather/v1/current?query=${city}&key=${apiKey}`;
axios.get(api).then(showWeather)};

function showWeather(event) {
  let displayTemperature = document.querySelector(".display-temperature");
  let displayIcon = document.querySelector(".display-icon");
  displayIcon.innerHTML = `<img src="${event.data.condition.icon_url}">`;
  displayTemperature.innerHTML = `<p></p><span class="temperature">The current temperature is ${Math.round(event.data.temperature.current)} °C</span>`;
}

function callFactApi(response){
  let api = `https://api.shecodes.io/ai/v1/generate?prompt=give_me_an_obscure_fact_about_${encodeURIComponent(response)}&context=output in basic HTML only use br tag and do not use underscores in your answer&key=${apiKey}`;
 axios.get(api).then(showFact);
;
}

function showFact(response){
  let displayFact = document.getElementById("display-fact");
  displayFact.innerHTML = `${response.data.answer}`; 
  console.log(response.data.answer);
}